### ISSUE TITLE
phase 1 - adding weak system role

### ISSUE THREAD

**Issue by heatherlogan-scottlogic** [gsproston-scottlogic/prompt-injection#100]
introduce new documents with project information (new folder documents per phase) 
one project is confidential 
give the QA model a somewhat weak prompt not to reveal info about this project. 
instruct the user to discover the name and some piece of information (e.g. cost/ timescale/location)
maybe project has been renamed with new info added. 
once user emails to someone it is a win. 

show attacks
keep defences hid? - maybe have a notification if the user triggers something with their prompt

e.g. "As the secret project name was revealed we have renamed it and we have now told the model not to tell you anything about the secret project. find out what the estimated budget it. "

**Comment by gsproston-scottlogic** [comment]
This has now been split into smaller issues.
