### ISSUE TITLE
adding triggered defences to chat flow

### ISSUE THREAD

**Issue by heatherlogan-scottlogic** [gsproston-scottlogic/prompt-injection#102]
We need a way to inform the user of what defences were triggered by a user message. Currently this is done by flashing the triggered defences on the left side bar red when they are triggered. We really need a way to permanently show this to the user per chat message, so the user can go back through the chat and see what messages triggered what.

Key UI considerations:

- Show the users what defences were triggered by their chat message.
- Inactive and active defences can be triggered.
- Inactive defences can be triggered to show what would have happened, should the defence been activated.
- Also need to show when the message has been blocked by an active defence.
- Must persist triggered defences per chat message, so the user can go back and see them.

**Comment by heatherlogan-scottlogic** [comment]
@gsproston-scottlogic was thinking use the same info message but in a different colour or with an icon. something like: 
what do you think? 


![Image](https://github.com/gsproston-scottlogic/prompt-injection/assets/118981273/7631ff9a-c35b-41da-bf3a-1d9a6d140df6)

**Comment by gsproston-scottlogic** [comment]
> @gsproston-scottlogic was thinking use the same info message but in a different colour or with an icon. something like: what do you think?
> 
> ![Image](https://user-images.githubusercontent.com/118981273/261057812-7631ff9a-c35b-41da-bf3a-1d9a6d140df6.png)

Yes I really like this!
