### ISSUE TITLE
Phase 0 Hide attacks, defences, and API key

### ISSUE THREAD

**Issue by gsproston-scottlogic** [gsproston-scottlogic/prompt-injection#105]
In the starting phase, hide the attack, defence, and API key components.

**Comment by heatherlogan-scottlogic** [comment]
do we also want to hide the model selection box? @gsproston-scottlogic

**Comment by gsproston-scottlogic** [comment]
> do we also want to hide the model selection box? @gsproston-scottlogic

Yeah I think so
