### ISSUE TITLE
Defence - Random sequence enclosure

### ISSUE THREAD

**Issue by gsproston-scottlogic** [gsproston-scottlogic/prompt-injection#15]
Puts the user input between random strings.

https://learnprompting.org/docs/prompt_hacking/defensive_measures/post_prompting

Each defence should include the following:

- A frontend component for the defensive measure on the left side bar.
- Checkbox to toggle the defensive measure.
- Some way to get a description of the defensive measure. 
- Pulsing the defensive measure component when it captures malicious content.

**Comment by asaha-scottlogic** [comment]
The link in the issue description should be 
https://learnprompting.org/docs/prompt_hacking/defensive_measures/random_sequence
