### ISSUE TITLE
AI will send email after refusing to do so

### ISSUE THREAD

**Issue by gsproston-scottlogic** [gsproston-scottlogic/prompt-injection#233]
https://drive.google.com/file/d/1CkUlGV1r79u0TPbRO5_SmuFT1uDUjGtI/view?usp=drive_link

**Comment by heatherlogan-scottlogic** [comment]
think this is solved with #249

![image](https://github.com/gsproston-scottlogic/prompt-injection/assets/118981273/17069220-3f73-478b-9720-a3be0294935f)

https://drive.google.com/file/d/1Eaaphc5EoFNB28R0KoWloZO8ypNyI_Kt/view?usp=drive_link
