### ISSUE TITLE
Defence - Filtering

### ISSUE THREAD

**Issue by heatherlogan-scottlogic** [gsproston-scottlogic/prompt-injection#44]
Use a blocklist of words and phrases to check user input for potential malicious content 

https://learnprompting.org/docs/prompt_hacking/defensive_measures/filtering

Each defence should include the following:

A frontend component for the defensive measure on the left side bar.
Checkbox to toggle the defensive measure.
Some way to get a description of the defensive measure.
Pulsing the defensive measure component when it captures malicious content.

**Comment by gsproston-scottlogic** [comment]
Removed this from the phase 2 milestone as it's not strictly needed.

**Comment by heatherlogan-scottlogic** [comment]
@gsproston-scottlogic  i was thinking of splitting this into two - one for filtering user input and one for bot output - what do you think?

**Comment by gsproston-scottlogic** [comment]
> @gsproston-scottlogic i was thinking of splitting this into two - one for filtering user input and one for bot output - what do you think?

Yeah that makes sense!
