### ISSUE TITLE
Internal documents - extended 

### ISSUE THREAD

**Issue by heatherlogan-scottlogic** [gsproston-scottlogic/prompt-injection#45]
Extend the MVP to have documents which include sensitive and non-sensitive information 
More research needed.
The LLM can decide what is sensitive (?) or we can instruct the LLM what should be considered as sensitive (?)

**Comment by gsproston-scottlogic** [comment]
Do you think we could close this now @heatherlogan-scottlogic  ?

**Comment by heatherlogan-scottlogic** [comment]
Yeah think so! didn't realise it was still open
