### ISSUE TITLE
Different LLMs

### ISSUE THREAD

**Issue by gsproston-scottlogic** [gsproston-scottlogic/prompt-injection#52]
Currently, the app uses ChatGPT 4. It would be interesting if the user is able to change what model is being used, even outside of OpenAI. 

Model options:

- ChatGPT 4
- ChatGPT 3.5
- [Claude 2](https://www.anthropic.com/index/claude-2)

**Comment by heatherlogan-scottlogic** [comment]
Created separate ticket #94 for using older models that are not supported by chat completions endpoint or functions

**Comment by heatherlogan-scottlogic** [comment]
On holding adding Claude as API only offered to limited set of users on an application basis. Will confirm before applying

**Comment by gsproston-scottlogic** [comment]
Closing this as I think if we want to add more specific models, we should have a new issue for each as it'll be pretty complex to add new ones now.
