### ISSUE TITLE
Add button to Reset all levels

### ISSUE THREAD

**Issue by smalyon-scottlogic** [gsproston-scottlogic/prompt-injection#566]
# Feature Request

## Description
Want a button so that I can reset game back to beginning regardless of current level.

## Screenshots
![Image](https://github.com/ScottLogic/prompt-injection/assets/130466114/71551725-9f3a-4a5a-bfe6-6dad03f5eec8)

## Additional context
[Figma](https://www.figma.com/file/dntI3xrEI40De9KDCMCmMI/AI-prompt-injection?type=design&node-id=335-1931&mode=dev)

When clicked, the button should show a confirmation modal. This should inform the user of exactly what progress will be lost (level progress, chat history, sent emails), and ask them if they're sure that they want to reset their progress.

Questions:

- We likely want some kind of confirmation after clicking this button. We don't want people misclicking it and losing all of their progress. How to do this? **- use pop-up modal**
- Disable button when only the first level is unlocked? **- no**
- Does this also reset chat history and that on level 1 and sandbox? **- yes, this button also clears individual level progress, including sandbox**
- Should it also reset sandbox defence configuration? **- no**

## Acceptance criteria
Ensure that colour contrast passes accessibility standards.
Firefox is good at this. There's an accessibility tab in dev tools where you can see colour contrast warnings.

**WHEN** the user clicks the button
**THEN** the confirmation modal is shown

**GIVEN** the user has clicked the button and is shown the confirmation modal
**WHEN** the user closes the modal by pressing escape 
**THEN** progress is NOT reset

**GIVEN** the user has clicked the button and is shown the confirmation modal
**WHEN** the user closes the modal by clicking off it
**THEN** progress is NOT reset

**GIVEN** the user has clicked the button and is shown the confirmation modal
**WHEN** the user chooses to NOT reset their progress
**THEN** the modal is closed
**AND** progress is NOT reset

**GIVEN** the user has clicked the button and is shown the confirmation modal
**WHEN** the user chooses to reset their progress
**THEN** the modal is closed
**AND** level progress is reset
**AND** all chat history is cleared
**AND** all emails are cleared

**GIVEN** the user is on level 1
**WHEN** the user resets their progress
**THEN** the user stays on level 1

**GIVEN** the user is on level 2
**WHEN** the user resets their progress
**THEN** the user is sent back to level 1

**GIVEN** the user is on level 3
**WHEN** the user resets their progress
**THEN** the user is sent back to level 1

**GIVEN** the user is on sandbox
**WHEN** the user resets their progress
**THEN** the user stays on sandbox

**GIVEN** the user is on sandbox
**WHEN** the user resets their progress
**THEN** all defence configuration remains the same

**Comment by pmarsh-scottlogic** [comment]
TESTING:
Reset progress button present and matching figma designs.
![image](https://github.com/ScottLogic/prompt-injection/assets/118171430/b4f67382-c036-4164-b89f-bc9071bf7380)


Confirmation modal appears on button press
![image](https://github.com/ScottLogic/prompt-injection/assets/118171430/21f31263-05c5-46c8-9056-56eae7527ad6)

"Esc" key, clicking off the modal and clicking cancel all close the modal and do not reset progress.

Clearing progress clears messages on all levels and re-locks levels 2 and 3. Sandbox defence configurations remain unchanged.

When on levels 2 or 3, and you reset, if you select "beginner" on the welcome modal then you are sent back to level 1.

All perfect! Moving to done
