### ISSUE TITLE
Add Get Started Button to Header

### ISSUE THREAD

**Issue by smalyon-scottlogic** [gsproston-scottlogic/prompt-injection#568]
# Feature Request

## Description
Want a get started button on header to initiate Get Started modal to display App overview.

## Screenshots
![image](https://github.com/ScottLogic/prompt-injection/assets/130466114/6c53ea07-ae9a-45cb-8661-6d326ed526a5)

## Additional context
[Figma](https://www.figma.com/file/dntI3xrEI40De9KDCMCmMI/AI-prompt-injection?type=design&node-id=335-1931&mode=dev)

This button will bring up the welcome modal again. Currently this is done by switching to and from story mode.

## Acceptance criteria
Ensure that colour contrast passes accessibility standards.
Firefox is good at this. There's an accessibility tab in dev tools where you can see colour contrast warnings.

**WHEN** the user clicks on the button
**THEN** the welcome modal is shown

**Comment by pmarsh-scottlogic** [comment]
TESTING:

![image](https://github.com/ScottLogic/prompt-injection/assets/118171430/dc3cee6d-655e-4553-b34d-5d16a49eab82)
There it is! Looks just like the designs. When you click it it opens the welcome modal. It is tabbable and has a good screenreader output too.

Moving to done
