### ISSUE TITLE
Update Handbook Button

### ISSUE THREAD

**Issue by smalyon-scottlogic** [gsproston-scottlogic/prompt-injection#569]
# Feature Request

## Description
Handbook button should be changed as per the current UX design.

## Screenshots
![image](https://github.com/ScottLogic/prompt-injection/assets/130466114/81b7d2d9-c275-4714-b2a2-366a34a208b0)

## Additional context
[Figma](https://www.figma.com/file/dntI3xrEI40De9KDCMCmMI/AI-prompt-injection?type=design&node-id=335-1931&mode=dev)

No real functionality change here, just updating the look of the button.

## Acceptance criteria
Ensure that colour contrast passes accessibility standards.
Firefox is good at this. There's an accessibility tab in dev tools where you can see colour contrast warnings.

**WHEN** the handbook button is clicked
**THEN** the handbook is shown

**Comment by dhinrichs-scottlogic** [comment]
testing

**Comment by dhinrichs-scottlogic** [comment]
Tested on Edge, Chrome and Firefox. Button looks fabulous:
![Image](https://github.com/ScottLogic/prompt-injection/assets/125262707/42899253-19bc-4fad-a574-7d43ab290f3f)
Handbook opens on click. 
Accessibility is good, too: icon has empty alt text (decorative only), text is clear, colour contrast is good. 

Moving this to done.
