### ISSUE TITLE
Update Chat Styles - Input Styles

### ISSUE THREAD

**Issue by smalyon-scottlogic** [gsproston-scottlogic/prompt-injection#573]
# Feature Request

## Description
Implement chat styles as per UX design.

## Screenshots
![Image](https://github.com/ScottLogic/prompt-injection/assets/130466114/e96f5784-41ea-4030-92da-d0e12bb44b0b)

## Additional context
[Figma](https://www.figma.com/file/dntI3xrEI40De9KDCMCmMI/AI-prompt-injection?type=design&node-id=301-534&mode=dev)

No functionality changes here (that's covered in #561), just UI updates.

## Acceptance criteria
Ensure that colour contrast passes accessibility standards.
Firefox is good at this. There's an accessibility tab in dev tools where you can see colour contrast warnings.

Just check buttons and input still work, and that they match the new updated UI.

**Comment by heatherlogan-scottlogic** [comment]
testing
