### ISSUE TITLE
Refactor  `chatGptSendMessage()`

### ISSUE THREAD

**Issue by pmarsh-scottlogic** [gsproston-scottlogic/prompt-injection#617]
method is 122 lines long, very nested and definitely not doing too well on the Single Responsibility front. I'd very much like it refactored and shortened before carrying out #493. To do this, I will separate big chunks of logic into smaller helper methods, and add [guard clauses](https://deviq.com/design-patterns/guard-clause) for unhappy paths.

This is a tricky ticket to write acceptance criteria for...

**Comment by gsproston-scottlogic** [comment]
TESTING 

As this is a refactor ticket, I'm just going to do some regression testing, making sure everything still works. Especially around chat bot communications.

**Comment by gsproston-scottlogic** [comment]
All looks good to me, checked general chatting, blocked messages, and transformed messages.
