### ISSUE TITLE
Email whitelist too strict

### ISSUE THREAD

**Issue by gsproston-scottlogic** [gsproston-scottlogic/prompt-injection#62]
The chat bot does not allow for sending to email addresses which aren't on the whitelist, even if the whitelist defence mechanism isn't active. When the defence is inactive, the chat bot should be able to send to any email address.

![image](https://github.com/gsproston-scottlogic/prompt-injection/assets/103250539/1cef5d55-c66d-464d-acc5-66aba4199458)

**Comment by heatherlogan-scottlogic** [comment]
I found that the bot was getting confused if you asked it "who am i allowed to email" it would return the list and kind of convince itself that you can't email anyone even when the defence is inactive. 

returning a "you can email anyone" from getEmailWhitelist when the defence is off works better for not confusing the bot. but with the limitation of not being able to tell you the whiltelist when the defence is off. 

you can still confuse it's responses by switching on/off and asking the questions in a sequence but should still send the email when defense is off and block when off at the email point e.g. 

![image](https://github.com/gsproston-scottlogic/prompt-injection/assets/118981273/2eb2c78b-2485-4d84-a7b2-01de1b53791a)
