### ISSUE TITLE
Backend health endpoint

### ISSUE THREAD

**Issue by gsproston-scottlogic** [gsproston-scottlogic/prompt-injection#622]
# Feature Request

## Description
Add a health check endpoint to the backend which the frontend can use to check the backend status.
http://localhost:3001/health

## Additional context
The frontend should check the backend health when the frontend starts.
If it fails, show an error to the user in the chat.

## Acceptance criteria
**GIVEN** backend is running
**WHEN** request made to endpoint http://localhost:3001/health
**THEN** endpoint returns 200

**GIVEN** backend is running normally
**WHEN** the frontend starts 
**THEN** no error is shown to the user

**GIVEN** backend is not running
**WHEN** the frontend starts 
**THEN** an error is shown to the user

**Comment by pmarsh-scottlogic** [comment]
Testing...
