### ISSUE TITLE
Common documents loaded four times, on server startup

### ISSUE THREAD

**Issue by chriswilty** [gsproston-scottlogic/prompt-injection#630]
# Bug report

## Description
Common documents are loaded four times on startup, which is wasteful. They should be loaded once and cached in memory, using a closure.

## Reproduction steps 
1. Load backend and observe logging output for document loading

## Expected behavior
Common documents are loaded from filesystem just once.

## Screenshots

![Image](https://github.com/ScottLogic/prompt-injection/assets/15246391/1fd9b0ad-c0fa-4e21-9dc5-15cb87263077)

## Acceptance criteria
**GIVEN** the backend is started
**WHEN** all documents are loaded
**THEN** common documents are loaded just once

**Comment by pmarsh-scottlogic** [comment]
Testing:
