### ISSUE TITLE
Don't export methods just for testing - defence.ts

### ISSUE THREAD

**Issue by gsproston-scottlogic** [gsproston-scottlogic/prompt-injection#641]
## Description
Currently we are exporting several functions for the sake of testing, even if they are only being used internally inside a module. The golden rule is, only test the API of a module. If you then find you need too much setup in your tests, then likely the module is doing too much, and is a candidate for splitting into different responsibilities.

## AC
This is a refactor ticket, so just regression testing here.

**Comment by heatherlogan-scottlogic** [comment]
testing
