### ISSUE TITLE
Add defence activation / deactivation to chat box

### ISSUE THREAD

**Issue by heatherlogan-scottlogic** [gsproston-scottlogic/prompt-injection#95]
When a user turns a defence on or off - a message is added to the centre chat box to help track flow of actions. 

example 
![image](https://github.com/gsproston-scottlogic/prompt-injection/assets/118981273/429161a7-496a-4a0c-a3b2-f2d0c94ffbde)

requires finalized ui desgin

**Comment by gsproston-scottlogic** [comment]
To be done after #104

**Comment by gsproston-scottlogic** [comment]
Combining with #104 for demo purposes.
