### ISSUE TITLE
phase 0 - easy break

### ISSUE THREAD

**Issue by heatherlogan-scottlogic** [gsproston-scottlogic/prompt-injection#99]
prompt to have a secret project that user can simply ask for 
hide defence/attack component 
preamble to instruct user on what to do (get name and email to some address). note it has no defences.
check for the win condition when email is sent.  

documents with some company info 
one document with a secret project that user can simply ask for 

no other documents with project info 

"we have told the model that one project is secret"

**Comment by gsproston-scottlogic** [comment]
Split into smaller tasks here https://github.com/gsproston-scottlogic/prompt-injection/milestone/1
